#!/usr/bin/env python3
"""Bundle the EPD42 Pomodoro CLI into one distributable file.

Deployment used to mean a clone of the repo (the CLI imports render / protocol /
ble_client / config from the sibling tools/epd-monitor folder), a Python venv,
uv and a 20 MB install.  This script emits ``dist/pomodoro.py``: one self
contained file with those four modules inlined plus the local state / face
modules, so a user only copies a single script.

Requirements after bundling:
  * Python 3.10+ and Pillow   -> render / status / start (计时 + 预览)
  * bleak (optional)          -> push / scan / describe / setdriver

    python build_single.py                 # -> dist/pomodoro.py
    python dist/pomodoro.py render --demo
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MONITOR = ROOT.parent / "epd-monitor"
OUT = ROOT / "dist" / "pomodoro.py"

_BUNDLE_PROLOGUE = '''\
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by build_single.py - one-file distribution of the EPD42 Pomodoro
# CLI (tools/epd-pomodoro).  Do not edit: regenerate instead.
#
# Requires Python 3.10+ and Pillow (`python -m pip install -r requirements.txt`).
# The BLE commands need bleak as well (`python -m pip install bleak`).
from __future__ import annotations

import sys as _sys
import types as _types


def _bundle(name: str, source: str) -> None:
    """Register ``source`` as module ``name`` so later imports resolve it.

    The module goes into ``sys.modules`` *before* its code runs: decorators
    such as ``@dataclass`` look up ``sys.modules[cls.__module__]`` while the
    class is being defined.
    """
    module = _types.ModuleType(name, f"<bundled {name}>")
    module.__package__ = ""
    _sys.modules[name] = module
    exec(compile(source, f"<bundled {name}.py>", "exec"), module.__dict__)


'''

# bleak is optional: only push/scan/describe/setdriver need it.  The proxies
# resolve on first use, so a render-only install works without installing it.
_BLEAK_LAZY = """\
# bleak 是可选依赖：只有 push/scan/describe/setdriver 需要它。这里的代理在
# 首次使用时才真正 import，纯渲染/计时的部署无需安装。
def _bleak():
    try:
        import bleak
    except ImportError as exc:
        raise RuntimeError(
            "蓝牙功能需要 bleak：pip install bleak（只渲染/计时无需安装）"
        ) from exc
    return bleak


class _BleakLazy:
    def __getattr__(self, name):
        return getattr(_bleak(), name)

    def __call__(self, *args, **kwargs):
        return _bleak().BleakClient(*args, **kwargs)


BleakClient: object = _BleakLazy()
BleakScanner: object = _BleakLazy()
"""

_BUNDLED_MODULES = (
    "config",
    "render",
    "protocol",
    "ble_client",
    "state",
    "face",
)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _ble_client_source() -> str:
    """bleak import replaced by the lazy proxy; providers import dropped."""
    out: list[str] = []
    for line in _read(MONITOR / "ble_client.py").splitlines():
        if line.strip() == "from bleak import BleakClient, BleakScanner":
            out.append(_BLEAK_LAZY)
        elif "from providers import SubscriptionItem" in line:
            continue
        else:
            out.append(line)
    return "\n".join(out)


def _pomodoro_source() -> str:
    """The CLI body minus the sibling-folder bootstrap of the dev version."""
    lines = _read(ROOT / "pomodoro.py").splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        if stripped.startswith("#!"):
            i += 1
        elif "from __future__ import" in stripped:
            i += 1
        elif stripped.startswith("_TOOLS ="):
            i += 1
        elif stripped.startswith("sys.path.insert("):
            depth = 0
            while i < len(lines):
                depth += lines[i].count("(") - lines[i].count(")")
                i += 1
                if depth <= 0:
                    break
        else:
            out.append(lines[i])
            i += 1
    return "\n".join(out)


def build(out: Path) -> Path:
    """Write the single-file bundle to *out* and return it."""
    parts = [_BUNDLE_PROLOGUE]
    for name in _BUNDLED_MODULES:
        if name == "ble_client":
            source = _ble_client_source()
        elif name == "state":
            source = _read(ROOT / "state.py")
        elif name == "face":
            source = _read(ROOT / "face.py")
        else:
            source = _read(MONITOR / f"{name}.py")
        parts.append(f"_bundle({name!r}, {source!r})\n\n")
    parts.append(_pomodoro_source())
    text = "".join(parts)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return out


def main() -> int:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT
    build(out)
    print(f"bundled -> {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
