"""Generate desktop/core/src/font_data.rs — bitmaps of the exact glyphs the
Rust face renderer needs, baked from the system fonts at dev time.

Run with a Pillow-capable interpreter:
    tools/epd-pomodoro/.venv/Scripts/python.exe desktop/tools/gen_font_rs.py
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

CONSOLAS = "C:/Windows/Fonts/consola.ttf"
MSYH = "C:/Windows/Fonts/msyh.ttc"
OUT = Path(__file__).resolve().parents[1] / "core" / "src" / "font_data.rs"

CONS16_ASCII = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 :-."  # 标题 POMODORO + 时间戳
MS16_CJK = "今日完成番茄第个"
MS16_DIGITS = "0123456789"
MS24_CJK = "剩分钟已暂停" + "\u00b7"
MS24_EXTRA = "0123456789/ "
MS34_CJK = "专注短休息长"
MS34_LATIN = "ABCDEFGHIJKLMNOPQRSTUVWXYZ "

TABLES = [
    ("CONS16", CONSOLAS, 16, CONS16_ASCII),
    ("MS16", MSYH, 16, MS16_CJK + MS16_DIGITS + " "),
    ("MS24", MSYH, 24, MS24_CJK + MS24_EXTRA),
    ("MS34", MSYH, 34, MS34_CJK + MS34_LATIN),
]


def glyph_bits(path: str, ch: str, size: int) -> tuple[int, int, int, int, int, list[int]]:
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    line_h = ascent + descent + 4
    canvas = Image.new("L", (size * 3, line_h), 255)
    draw = ImageDraw.Draw(canvas)
    draw.text((2, 2), ch, font=font, fill=0, anchor="la")
    mask = canvas.point(lambda p: 255 - p)  # ink -> 255
    bbox = mask.getbbox()
    if bbox is None:  # space 等空字形
        advance = max(1, round(font.getlength(ch)))
        return advance, 0, 0, 1, 1, [0]
    x0, y0, x1, y1 = bbox
    w = x1 - x0
    h = y1 - y0
    rows = int((w + 7) // 8)
    bits: list[int] = []
    for y in range(y0, y1):
        byte = 0
        for x in range(x0, x1):
            if mask.getpixel((x, y)) > 127:
                byte |= 0x80 >> (x - x0) % 8
            if (x - x0) % 8 == 7:
                bits.append(byte)
                byte = 0
        if w % 8 != 0:
            bits.append(byte)
    advance = max(1, round(font.getlength(ch)))
    return advance, x0 - 2, y0 - 2, w, h, bits


def emit() -> str:
    lines = [
        "// @generated by desktop/tools/gen_font_rs.py — 不要手改。",
        "// 运行时零字体依赖：沙漏画面所需字符的位图从系统字体一次性烘焙。",
        "#![allow(clippy::all)]",
        "",
        "pub struct Glyph {",
        "    pub advance: u16,",
        "    pub x0: i8,"
        "    pub y0: i8,"
        "    pub w: u8,",
        "    pub h: u8,",
        "    pub bits: &'static [u8],",
        "}",
        "",
    ]
    for name, _path, size, chars in TABLES:
        ascent, descent = ImageFont.truetype(_path, size).getmetrics()
        lines.append(f"pub const {name}_METRICS: (u16, u16) = ({ascent}, {descent});")
    lines.append("")
    for name, path, size, chars in TABLES:
        lines.append(f"pub const {name}: &[(char, Glyph)] = &[")
        for ch in chars:
            advance, x0, y0, w, h, bits = glyph_bits(path, ch, size)
            bits_str = ", ".join(str(b) for b in bits)
            lines.append(
                f"    ('{ch}', Glyph {{ advance: {advance}, x0: {x0}, y0: {y0}, "
                f"w: {w}, h: {h}, bits: &[{bits_str}] }}),"
            )
        lines.append("];")
        lines.append("")
    lines.append(
        "pub fn lookup(table: &'static [(char, Glyph)], ch: char) -> Option<&'static Glyph> {"
    )
    lines.append("    table.iter().find(|(c, _)| *c == ch).map(|(_, g)| g)")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT.write_text(emit(), encoding="utf-8")
    print(f"written {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()